server:
  port: 8181
spring:
  datasource:
    password: fission
    url: jdbc:postgresql://localhost:5433/resource-radar
    username: fission
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true